### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by cydrollinger** [makerdiary/nrf52832-mdk#17]
running this recipe for linux unbuntu and trying to build the project hello_world, the cmake is not up to date and fails!

**Comment by caizelin** [comment]
> running this recipe for linux unbuntu and trying to build the project hello_world, the cmake is not up to date and fails!

@cydrollinger Hi, which example are you trying to build? Thanks for your feedback.

**Comment by cydrollinger** [comment]
No worries, I think I may have confused this with the Zephyr project
