### ISSUE TITLE
佩服

### ISSUE THREAD

**Issue by jiuxiaxixi** [makerdiary/nrf52832-mdk#3]

**Comment by jiuxiaxixi** [comment]
你涉及的领域真的很广！请问网站是怎么弄的呢？ 是开源的么？好漂亮！我也想做一个类似的

**Comment by makerdiary** [comment]
@jiuxiaxixi 网站使用开源的 mkdocs，主题采用 Material for MkDocs

**Comment by jiuxiaxixi** [comment]
非常感谢！！！ 现在是流行混搭么？ 
MCU+WEB+LINUX

**Comment by jiuxiaxixi** [comment]
@makerdiary

**Comment by makerdiary** [comment]
@jiuxiaxixi 个人爱好，非主流，入坑需谨慎 :)
