### ISSUE TITLE
MSYS下使用pip 无效

### ISSUE THREAD

**Issue by tuyafei** [makerdiary/nrf52832-mdk#4]

**Comment by makerdiary** [comment]
@tuyafei 需要安装python，可以使用以下命令安装：
```
pacman -S python2 python3
```
![](https://img.makerdiary.co/wiki/nrf52832mdk/msys_pip_version.png)

**Comment by makerdiary** [comment]
@tuyafei 如果没有其他问题，该issue就暂时关闭了，有需要可以重新打开，Thanks.
