### ISSUE TITLE
DAPlink

### ISSUE THREAD

**Issue by xiaolongba** [makerdiary/nrf52832-mdk#6]
你好，我看了daplink的github上看到，有很多个lpc11u35的bin文件，我应该下载哪个daplink的固件？我没看到有关于52832的daplink，还望大佬指示

**Comment by makerdiary** [comment]
@xiaolongba 感谢反馈，已经上传新的 DAPLINK 固件。[查看固件](https://github.com/makerdiary/nrf52832-mdk/tree/master/bin)

**Comment by xiaolongba** [comment]
@makerdiary 
我有两个问题想问下大佬：
1、我下载进去之后，发现映射出来的U盘是63.9MB，这个是有问题的吧？Nordic 52832的Flash大小才512KB
2、如果我想把这个移植到烧录其他的CortexM核的MCU可以吗？

**Comment by makerdiary** [comment]
@xiaolongba 
1、64MB是正常的，针对52832的话如果bin档大小超出512KB是写不进去的，会自动报错
2、可以移植，有一定工作量。目前官方支持的target不多。

**Comment by xiaolongba** [comment]
@makerdiary 谢谢大佬，如果能搞个移植的教程就perfect了

**Comment by makerdiary** [comment]
@xiaolongba 该issue先关闭了，有问题可以再次打开
