### ISSUE TITLE
where is the reference of "NRF_LOG_BACKEND_SERIAL_UART_RX_PIN"

### ISSUE THREAD

**Issue by cafuck** [makerdiary/nrf52832-mdk#7]
WiKi specified
TX ↔ P20
RX ↔ P19

but the Macro I cannot figure out where to use
#define NRF_LOG_BACKEND_SERIAL_UART_TX_PIN 20
#define NRF_LOG_BACKEND_SERIAL_UART_RX_PIN 19

**Comment by makerdiary** [comment]
@cafuck The input function has been removed from log module since SDK 14. You can CLI(Command Line Interface) library instead.
