### ISSUE TITLE
My mobile phone can not connect to nrf52

### ISSUE THREAD

**Issue by fredtsai** [makerdiary/nrf52832-mdk#8]
Hi

1. BLE LED image(nrf52-DK mbed source code) burn into the nrf52-DK
使用mbed提供的BLE LED代碼,燒入到nrf52-DK

2. download nRF Connect app for test
手機下載nrf connect app 做測試

3. Search device -> can search for LED
可搜尋到LED這個裝置

4. Click CONNECT
點選connect連線

result:
CONNECTING ... -> DISCONVERING ... -> DISCONNECTED
結果無法連線成功,看起來是找不到character

fred_tsai@goldtek.com
Thanks 
Fred

**Comment by makerdiary** [comment]
Hi Fred，
只看现象比较难定位问题，你可以输出一些log以便查看具体是哪一步没成功。
如果从log自己无法判断，你可以在这里附上输出的log，以便大家定位问题。

Thanks
Zelin
